### ISSUE TITLE
Keys containing parentheses are invalid

### ISSUE THREAD

**Issue by Tom-McQuillan** [JKISoftware/toml-edit-labview#4]
For example:
```
[vipm.dependencies]
national_instruments_lib_nipm_api_(beta) = "3.2.1.9"
```
will return an error because beta is within parentheses.

In the context of Dragon this will happen fairly often.

**Comment by jimkring** [comment]
Hey @Tom-McQuillan.

`national_instruments_lib_nipm_api_(beta)` (without quotes) is not a valid TOML keyname.  It should be wrapped in quotes, to be valid:

```toml
[vipm.dependencies]
"national_instruments_lib_nipm_api_(beta)" = "3.2.1.9"
```

As such, this is more of a Dragon error than a toml-edit-labview library error. Ping me for some ideas...

**Comment by jimkring** [comment]
Side note: The toml-edit-labview library now outputs toml parsing error details (specific line in the toml) when trying to load TOML data (e.g. the  `toml.lvclass:from_string.vi` VI)
